source 'https://github.com/igagis/cocoapods-repo.git'

project 'rasterimage/rasterimage.xcodeproj'

platform :ios, '11.0'

target "rasterimage" do
	pod 'utki', '>= 1.1.211'
	pod 'papki', '>= 1.0.129'
	pod 'r4', '>= 1.0.75'
	pod 'jpeg', '>= 6.1.1.11'
	pod 'png', '>= '1.6.39.1'
end
